# Tapşırıq 24.

## Keçən il mağazalarımıza mütəmadi çörək təchizatı ilə bağlı problem yaşayırdıq. Bir çox hallarda, müştərilərin çox olan vaxtında artıq çörəklər bitmiş olur, bəzən isə uyğun olmayan vaxtda gətirilən çörəklər növbəti günə qalırdı. Bu il bu problemin yaranmasını istəmirəm, zəhmət olmasa ötən il hər bir filial üzrə 3 saatdan bir neçə çörək satıldığını qrafik və ya cədvəl şəklində hazırlayın.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("esas_mehsullar.csv")
df = data.copy()
df.head()

,column_a,satish_kodu,mehsul_kodu,mehsul_ad,mehsul_kateqoriya,mehsul_qiymet,satish_tarixi,endirim_kompaniya,bonus_kart,magaza_ad,magaza_lat,magaza_long,magaza_location
0,0,577571,3334,GONDOL SIMPLE LABABO VE BUZLUK HALISI G61*50,Məişət məhsulları,3.68,2019-07-19T12:29:00,Sərin Yay günləri,True,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)
1,1,577571,4674,TAXTA BICAQ 3232,Qab-qacaq,2.25,2019-07-19T12:29:00,Sərin Yay günləri,True,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)
2,2,577571,8388,VITA 1LT ANANAS SIRESI,Meyvə Şirələri,2.50,2019-07-19T12:29:00,Sərin Yay günləri,True,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)
3,3,577571,6017,GILAN BAGDAN 1LT SARI GAVALI KOMPOTU,Kompotlar,1.45,2019-07-19T12:29:00,Sərin Yay günləri,True,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)
4,4,577571,8297,OSRAM SUPERSTAR LAMPA 64544A ECO 57W E27,Məişət məhsulları,2.92,2019-07-19T12:29:00,Sərin Yay günləri,True,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)

In [3]:
df["mehsul_kateqoriya"].unique()

array(['Məişət məhsulları', 'Qab-qacaq', 'Meyvə Şirələri', 'Kompotlar',
       'Turşular', ' Kofe, kakao və s. ', 'Şirniyyat', 'Şərablar',
       'Yağlar', 'Quru meyvə paketli', 'Ayaqqabı ləvazimatları',
       ' Yuyucu, təmizləyicilər ', 'Tütün məhsulları', 'Ədviyyatlar',
       'Kolbasa və sosislər', 'Araq', 'Diabetik', 'Dənlilər',
       'Plastik qablar', 'Qab yumaq üçün', 'Enerji içkiləri',
       'Qatılaşdırılmış süd', 'Corablar', 'Bayram aksessuarları', 'Sular',
       'Paltarlar üçün', 'Un məmulatları', 'Quru meyvələr', 'Dondurma',
       'Yogurt', 'Tekstil', 'Çörək', 'Pendirlər', 'Çay', 'Кəsmik', 'Xama',
       'Pivələr', 'Konservlər', 'Meyvə', 'Unlar', 'Qatıq',
       'Konservləşdirilmiş tərəvəz', ' Viski,tekila və s. ', 'Souslar',
       'Saqqızlar', 'Batareya', 'Soyuq Çaylar', 'Tərəvəz',
       'Həşəratlara qarşı', 'Kefir', 'Qaymaq', 'Şor', 'Kolalar', 'Avto',
       'Süd', 'Kokteyllər', 'Konyak', 'Zeytunlar', 'Ayran',
       'Hazır yeməklər', 'Səhər yeməkləri', 'Şampan', 'Dovğa',
       'Donmuş məhsullar', 'Dondurulmuş məhsullar', '1', 'Göyərti'],
      dtype=object)

In [4]:
# çörək datasını seçmək

corek_df = df[df["mehsul_kateqoriya"] == "Çörək"].copy()

In [5]:
corek_df

,column_a,satish_kodu,mehsul_kodu,mehsul_ad,mehsul_kateqoriya,mehsul_qiymet,satish_tarixi,endirim_kompaniya,bonus_kart,magaza_ad,magaza_lat,magaza_long,magaza_location
83,83,385937,2750,COREK COREKCI 450GR KOMBE COVDARLI,Çörək,0.50,2019-02-06T03:22:00,NaN,True,Yeni Yasamal,40.393613,49.790698,POINT(49.7906977 40.3936129)
91,91,980107,8272,TENDIR T.KICIK,Çörək,0.50,2019-01-15T02:48:00,Yeni il fürsətləri,False,N.Nərimanov,40.396347,49.872752,POINT(49.872752 40.396347)
205,205,375952,2988,EL EMEYI NAXCIVAN LAVASI,Çörək,0.65,2019-08-20T07:43:00,Sərin Yay günləri,False,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)
227,227,912250,3347,N1 ZAVOD 400GR COVDAR KURE COREYI,Çörək,0.50,2019-04-18T18:16:00,NaN,True,N.Nərimanov,40.396347,49.872752,POINT(49.872752 40.396347)
259,259,512941,6854,FIRIN.COREK COVDARLI 250GR BATON EDED,Çörək,0.50,2019-10-12T00:57:00,NaN,True,Xalqlar dostluğu,40.394605,49.953685,POINT(49.953685 40.394605)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
437598,437598,520882,3189,LAVAS SEDEREK TENDIR 4 EDED,Çörək,0.55,2019-02-26T08:44:00,NaN,False,Ayna Sultanova,40.414309,49.841997,POINT(49.8419972 40.4143087)
437903,437903,353525,3085,XAN COREK,Çörək,1.15,2019-10-30T20:15:00,NaN,True,Badamdar,40.332686,49.799567,POINT(49.7995673 40.3326856)
437960,437960,812186,2921,COREK IVANOVKA 500GR PEHRIZ COVDAR,Çörək,0.75,2019-01-20T22:28:00,Yeni il fürsətləri,True,Maşın bazarı,40.388683,49.868089,POINT(49.8680888 40.3886828)
438273,438273,982566,7335,COREK BURGER BREAD,Çörək,0.40,2019-07-12T05:46:00,NaN,True,Xalqlar dostluğu,40.394605,49.953685,POINT(49.953685 40.394605)
438396,438396,562761,5852,FIRIN.SUXARI EDED,Çörək,0.50,2019-07-21T01:30:00,Sərin Yay günləri,False,20 yanvar,40.395360,49.818190,POINT(49.81819 40.39536)

In [6]:
# satish_tarixi sütununu saat formatına çevirmək

corek_df["satish_tarixi"] = pd.DatetimeIndex(corek_df["satish_tarixi"]).strftime("%H:%M:%S")

In [7]:
corek_df

,column_a,satish_kodu,mehsul_kodu,mehsul_ad,mehsul_kateqoriya,mehsul_qiymet,satish_tarixi,endirim_kompaniya,bonus_kart,magaza_ad,magaza_lat,magaza_long,magaza_location
83,83,385937,2750,COREK COREKCI 450GR KOMBE COVDARLI,Çörək,0.50,03:22:00,NaN,True,Yeni Yasamal,40.393613,49.790698,POINT(49.7906977 40.3936129)
91,91,980107,8272,TENDIR T.KICIK,Çörək,0.50,02:48:00,Yeni il fürsətləri,False,N.Nərimanov,40.396347,49.872752,POINT(49.872752 40.396347)
205,205,375952,2988,EL EMEYI NAXCIVAN LAVASI,Çörək,0.65,07:43:00,Sərin Yay günləri,False,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)
227,227,912250,3347,N1 ZAVOD 400GR COVDAR KURE COREYI,Çörək,0.50,18:16:00,NaN,True,N.Nərimanov,40.396347,49.872752,POINT(49.872752 40.396347)
259,259,512941,6854,FIRIN.COREK COVDARLI 250GR BATON EDED,Çörək,0.50,00:57:00,NaN,True,Xalqlar dostluğu,40.394605,49.953685,POINT(49.953685 40.394605)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
437598,437598,520882,3189,LAVAS SEDEREK TENDIR 4 EDED,Çörək,0.55,08:44:00,NaN,False,Ayna Sultanova,40.414309,49.841997,POINT(49.8419972 40.4143087)
437903,437903,353525,3085,XAN COREK,Çörək,1.15,20:15:00,NaN,True,Badamdar,40.332686,49.799567,POINT(49.7995673 40.3326856)
437960,437960,812186,2921,COREK IVANOVKA 500GR PEHRIZ COVDAR,Çörək,0.75,22:28:00,Yeni il fürsətləri,True,Maşın bazarı,40.388683,49.868089,POINT(49.8680888 40.3886828)
438273,438273,982566,7335,COREK BURGER BREAD,Çörək,0.40,05:46:00,NaN,True,Xalqlar dostluğu,40.394605,49.953685,POINT(49.953685 40.394605)
438396,438396,562761,5852,FIRIN.SUXARI EDED,Çörək,0.50,01:30:00,Sərin Yay günləri,False,20 yanvar,40.395360,49.818190,POINT(49.81819 40.39536)

In [8]:
# tarix formatına çevirmək

corek_df["satish_tarixi"] = corek_df["satish_tarixi"].astype("datetime64")

In [9]:
corek_df

,column_a,satish_kodu,mehsul_kodu,mehsul_ad,mehsul_kateqoriya,mehsul_qiymet,satish_tarixi,endirim_kompaniya,bonus_kart,magaza_ad,magaza_lat,magaza_long,magaza_location
83,83,385937,2750,COREK COREKCI 450GR KOMBE COVDARLI,Çörək,0.50,2020-09-20 03:22:00,NaN,True,Yeni Yasamal,40.393613,49.790698,POINT(49.7906977 40.3936129)
91,91,980107,8272,TENDIR T.KICIK,Çörək,0.50,2020-09-20 02:48:00,Yeni il fürsətləri,False,N.Nərimanov,40.396347,49.872752,POINT(49.872752 40.396347)
205,205,375952,2988,EL EMEYI NAXCIVAN LAVASI,Çörək,0.65,2020-09-20 07:43:00,Sərin Yay günləri,False,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)
227,227,912250,3347,N1 ZAVOD 400GR COVDAR KURE COREYI,Çörək,0.50,2020-09-20 18:16:00,NaN,True,N.Nərimanov,40.396347,49.872752,POINT(49.872752 40.396347)
259,259,512941,6854,FIRIN.COREK COVDARLI 250GR BATON EDED,Çörək,0.50,2020-09-20 00:57:00,NaN,True,Xalqlar dostluğu,40.394605,49.953685,POINT(49.953685 40.394605)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
437598,437598,520882,3189,LAVAS SEDEREK TENDIR 4 EDED,Çörək,0.55,2020-09-20 08:44:00,NaN,False,Ayna Sultanova,40.414309,49.841997,POINT(49.8419972 40.4143087)
437903,437903,353525,3085,XAN COREK,Çörək,1.15,2020-09-20 20:15:00,NaN,True,Badamdar,40.332686,49.799567,POINT(49.7995673 40.3326856)
437960,437960,812186,2921,COREK IVANOVKA 500GR PEHRIZ COVDAR,Çörək,0.75,2020-09-20 22:28:00,Yeni il fürsətləri,True,Maşın bazarı,40.388683,49.868089,POINT(49.8680888 40.3886828)
438273,438273,982566,7335,COREK BURGER BREAD,Çörək,0.40,2020-09-20 05:46:00,NaN,True,Xalqlar dostluğu,40.394605,49.953685,POINT(49.953685 40.394605)
438396,438396,562761,5852,FIRIN.SUXARI EDED,Çörək,0.50,2020-09-20 01:30:00,Sərin Yay günləri,False,20 yanvar,40.395360,49.818190,POINT(49.81819 40.39536)

In [10]:
# indexi tarix qeyd etmək

corek_df.set_index(corek_df["satish_tarixi"], inplace=True)
corek_df

,column_a,satish_kodu,mehsul_kodu,mehsul_ad,mehsul_kateqoriya,mehsul_qiymet,satish_tarixi,endirim_kompaniya,bonus_kart,magaza_ad,magaza_lat,magaza_long,magaza_location
satish_tarixi,,,,,,,,,,,,,
2020-09-20 03:22:00,83,385937,2750,COREK COREKCI 450GR KOMBE COVDARLI,Çörək,0.50,2020-09-20 03:22:00,NaN,True,Yeni Yasamal,40.393613,49.790698,POINT(49.7906977 40.3936129)
2020-09-20 02:48:00,91,980107,8272,TENDIR T.KICIK,Çörək,0.50,2020-09-20 02:48:00,Yeni il fürsətləri,False,N.Nərimanov,40.396347,49.872752,POINT(49.872752 40.396347)
2020-09-20 07:43:00,205,375952,2988,EL EMEYI NAXCIVAN LAVASI,Çörək,0.65,2020-09-20 07:43:00,Sərin Yay günləri,False,Zabrat,40.485561,49.946741,POINT(49.9467409 40.4855613)
2020-09-20 18:16:00,227,912250,3347,N1 ZAVOD 400GR COVDAR KURE COREYI,Çörək,0.50,2020-09-20 18:16:00,NaN,True,N.Nərimanov,40.396347,49.872752,POINT(49.872752 40.396347)
2020-09-20 00:57:00,259,512941,6854,FIRIN.COREK COVDARLI 250GR BATON EDED,Çörək,0.50,2020-09-20 00:57:00,NaN,True,Xalqlar dostluğu,40.394605,49.953685,POINT(49.953685 40.394605)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-20 08:44:00,437598,520882,3189,LAVAS SEDEREK TENDIR 4 EDED,Çörək,0.55,2020-09-20 08:44:00,NaN,False,Ayna Sultanova,40.414309,49.841997,POINT(49.8419972 40.4143087)
2020-09-20 20:15:00,437903,353525,3085,XAN COREK,Çörək,1.15,2020-09-20 20:15:00,NaN,True,Badamdar,40.332686,49.799567,POINT(49.7995673 40.3326856)
2020-09-20 22:28:00,437960,812186,2921,COREK IVANOVKA 500GR PEHRIZ COVDAR,Çörək,0.75,2020-09-20 22:28:00,Yeni il fürsətləri,True,Maşın bazarı,40.388683,49.868089,POINT(49.8680888 40.3886828)
2020-09-20 05:46:00,438273,982566,7335,COREK BURGER BREAD,Çörək,0.40,2020-09-20 05:46:00,NaN,True,Xalqlar dostluğu,40.394605,49.953685,POINT(49.953685 40.394605)
2020-09-20 01:30:00,438396,562761,5852,FIRIN.SUXARI EDED,Çörək,0.50,2020-09-20 01:30:00,Sərin Yay günləri,False,20 yanvar,40.395360,49.818190,POINT(49.81819 40.39536)

In [11]:
# tarixi 3 saat aralığında bölmək

corek_df.resample("3H").size()

satish_tarixi
2020-09-20 00:00:00    357
2020-09-20 03:00:00    346
2020-09-20 06:00:00    355
2020-09-20 09:00:00    357
2020-09-20 12:00:00    334
2020-09-20 15:00:00    364
2020-09-20 18:00:00    356
2020-09-20 21:00:00    348
Freq: 3H, dtype: int64

In [12]:
# hər mağaza üzrə 3 saat aralığındakı satış sayı

corek_df.resample("3H")["magaza_ad"].value_counts()

satish_tarixi        magaza_ad
2020-09-20 00:00:00  Həzi Aslanov-1       26
                     20 yanvar            25
                     Yasamal              24
                     C. Məmmədquluzadə    22
                     8 mkr                20
                                          ..
2020-09-20 21:00:00  Həzi Aslanov-2       13
                     Radiozavod           13
                     Yeni Yasamal         13
                     Əhmədli              13
                     Hipermarket          12
Name: magaza_ad, Length: 168, dtype: int64

In [13]:
# dataframe-ə çevirmək

new_df = corek_df.resample("3H")["magaza_ad"].value_counts().to_frame()
new_df

                                       magaza_ad
satish_tarixi       magaza_ad
2020-09-20 00:00:00 Həzi Aslanov-1            26
                    20 yanvar                 25
                    Yasamal                   24
                    C. Məmmədquluzadə         22
                    8 mkr                     20
...                                          ...
2020-09-20 21:00:00 Həzi Aslanov-2            13
                    Radiozavod                13
                    Yeni Yasamal              13
                    Əhmədli                   13
                    Hipermarket               12

[168 rows x 1 columns]

In [14]:
new_df.rename(columns={"magaza_ad" : "satis_sayi"}, inplace = True)

In [15]:
new_df

                                       satis_sayi
satish_tarixi       magaza_ad
2020-09-20 00:00:00 Həzi Aslanov-1             26
                    20 yanvar                  25
                    Yasamal                    24
                    C. Məmmədquluzadə          22
                    8 mkr                      20
...                                           ...
2020-09-20 21:00:00 Həzi Aslanov-2             13
                    Radiozavod                 13
                    Yeni Yasamal               13
                    Əhmədli                    13
                    Hipermarket                12

[168 rows x 1 columns]

In [16]:
new_df = new_df.reset_index()
new_df

          satish_tarixi          magaza_ad  satis_sayi
0   2020-09-20 00:00:00     Həzi Aslanov-1          26
1   2020-09-20 00:00:00          20 yanvar          25
2   2020-09-20 00:00:00            Yasamal          24
3   2020-09-20 00:00:00  C. Məmmədquluzadə          22
4   2020-09-20 00:00:00              8 mkr          20
..                  ...                ...         ...
163 2020-09-20 21:00:00     Həzi Aslanov-2          13
164 2020-09-20 21:00:00         Radiozavod          13
165 2020-09-20 21:00:00       Yeni Yasamal          13
166 2020-09-20 21:00:00            Əhmədli          13
167 2020-09-20 21:00:00        Hipermarket          12

[168 rows x 3 columns]

In [17]:
# satish_tarixi dəyişənini saatlara çevirmək

new_df["satish_tarixi"] = pd.DatetimeIndex(new_df["satish_tarixi"]).hour

In [18]:
new_df

     satish_tarixi          magaza_ad  satis_sayi
0                0     Həzi Aslanov-1          26
1                0          20 yanvar          25
2                0            Yasamal          24
3                0  C. Məmmədquluzadə          22
4                0              8 mkr          20
..             ...                ...         ...
163             21     Həzi Aslanov-2          13
164             21         Radiozavod          13
165             21       Yeni Yasamal          13
166             21            Əhmədli          13
167             21        Hipermarket          12

[168 rows x 3 columns]

In [19]:
new_df.rename(columns={"satish_tarixi" : "saat"}, inplace=True)
new_df

     saat          magaza_ad  satis_sayi
0       0     Həzi Aslanov-1          26
1       0          20 yanvar          25
2       0            Yasamal          24
3       0  C. Məmmədquluzadə          22
4       0              8 mkr          20
..    ...                ...         ...
163    21     Həzi Aslanov-2          13
164    21         Radiozavod          13
165    21       Yeni Yasamal          13
166    21            Əhmədli          13
167    21        Hipermarket          12

[168 rows x 3 columns]

In [20]:
# saat dəyişənini saat aralığına çevirmək 

saatlar = {0:"00:00-03:00", 3:"03:00-06:00",6:"06:00-09:00",9:"09:00-12:00",12:"12:00-15:00",
           15:"15:00-18:00",18:"18:00-21:00",21:"21:00-00:00"}

new_df["saat"].replace(saatlar, inplace = True)

In [21]:
new_df

            saat          magaza_ad  satis_sayi
0    00:00-03:00     Həzi Aslanov-1          26
1    00:00-03:00          20 yanvar          25
2    00:00-03:00            Yasamal          24
3    00:00-03:00  C. Məmmədquluzadə          22
4    00:00-03:00              8 mkr          20
..           ...                ...         ...
163  21:00-00:00     Həzi Aslanov-2          13
164  21:00-00:00         Radiozavod          13
165  21:00-00:00       Yeni Yasamal          13
166  21:00-00:00            Əhmədli          13
167  21:00-00:00        Hipermarket          12

[168 rows x 3 columns]

In [22]:
# hər mağaza üzrə verilmiş saat aralığındakı çörək satışları

satislar = pd.pivot_table(new_df, "satis_sayi", "saat","magaza_ad",aggfunc="sum")
satislar

magaza_ad,20 yanvar,28-May,8 mkr,Ayna Sultanova,Badamdar,C. Məmmədquluzadə,Hipermarket,Həzi Aslanov-1,Həzi Aslanov-2,M. Əcəmi,...,N.Nərimanov,Nərimanov-2,Radiozavod,Xalqlar dostluğu,Xırdalan,Xətai,Yasamal,Yeni Yasamal,Zabrat,Əhmədli
saat,,,,,,,,,,,,,,,,,,,,,
00:00-03:00,25,14,20,12,19,22,7,26,15,17,...,18,18,15,19,18,17,24,10,12,20
03:00-06:00,19,17,17,13,18,17,15,12,14,20,...,18,13,20,18,15,16,12,17,15,16
06:00-09:00,18,12,11,22,13,21,22,18,12,19,...,14,20,19,18,19,18,13,14,20,13
09:00-12:00,19,18,16,14,22,16,17,14,21,19,...,16,19,21,23,16,14,12,15,16,11
12:00-15:00,13,17,16,14,8,23,17,12,19,20,...,17,17,20,17,17,11,18,6,12,18
15:00-18:00,17,13,17,25,13,22,15,7,18,13,...,16,19,18,26,14,15,17,15,25,16
18:00-21:00,25,14,12,13,17,12,16,19,19,29,...,19,19,12,13,13,20,17,17,17,18
21:00-00:00,22,20,16,13,13,15,12,21,13,29,...,20,15,13,16,14,14,16,13,25,13

In [23]:
# excel formatında cədvələ çevirmək

satislar.to_excel("corek_satis.xlsx")